"""initial migration

Revision ID: 3272743eaa38
Revises: 5a52d77535c5
Create Date: 2024-01-25 18:15:29.941338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3272743eaa38'
down_revision = '5a52d77535c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fatura_id', table_name='fatura')
    op.drop_table('fatura')
    op.drop_index('ix_itemDesejo_id', table_name='itemdesejo')
    op.drop_table('itemdesejo')
    op.drop_index('email', table_name='usuario')
    op.drop_index('ix_usuario_id', table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('senha', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('ativo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('dia_fatura', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_usuario_id', 'usuario', ['id'], unique=False)
    op.create_index('email', 'usuario', ['email'], unique=False)
    op.create_table('itemdesejo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('descricao', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('prioridade', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preco', mysql.FLOAT(), nullable=True),
    sa.Column('adquirido', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='fk_usuario_itemDesejo'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_itemDesejo_id', 'itemdesejo', ['id'], unique=False)
    op.create_table('fatura',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nomeInstituicao', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('nomeFatura', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('valor', mysql.FLOAT(), nullable=True),
    sa.Column('parcelas', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='fk_usuario_fatura'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_fatura_id', 'fatura', ['id'], unique=False)
    # ### end Alembic commands ###
